version: '3'
services:
  app:
    container_name: docker-library
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongod
  mongod:
    container_name: mongod
    image: mongo
    ports:
      - '27019:27019'